baseURL = 'https://wellzhi.github.io'
languageCode = 'en-us'
title = 'Wellzhi'
theme = "hugo-PaperMod"

[params]
defaultTheme = "auto"  # 主题模式 (auto, light, dark)
showReadingTime = true
showWordCount = true
showDate = true
authors = true
disableSearch = false
ShowCodeCopyButtons = true
ShowShareButtons = true
ShowToc = true
TocOpen = false
author = [ "wellzhi"]


[params.homeInfoParams]
Title = "Hi"
Content = "I'm a software engineer. I write about programming, software development, and technology. I'm passionate about learning and sharing knowledge. I hope you find my blog helpful."

# 社交图标配置
[[params.socialIcons]]
name = "Twitter"
url = "https://github.com/wellzhi"
icon = "fa-brands fa-twitter"

[[params.socialIcons]]
name = "StackOverflow"
url = "https://github.com/wellzhi"
icon = "fa-brands fa-stack-overflow"

[[params.socialIcons]]
name = "CodePen"
url = "https://codepen.io/your_username"
icon = "fa-brands fa-codepen"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://github.com/wellzhi"
icon = "fa-brands fa-linkedin"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/wellzhi"
icon = "fa-brands fa-github"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Post"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Archive"
url = "/archives"
weight = 3
[[menu.main]]
name = "Search"
url = "/search"
weight = 4
[[menu.main]]
name = "About"
url = "/about/"
weight = 5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]