[project]
name = "python-shell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "config>=0.5.1",
    "oss2>=2.19.1",
    "pillow>=11.3.0",
]
